import unittest
import sys
import os

DIRNAME = os.path.dirname(__file__)

sys.path.insert(0, os.path.join(DIRNAME, "../src"))
import gbif_api

test_caseImput = [
    "Zizaniopsis bonariensis (Balansa & Poitr.) Speg."
]

test_caseOutput = {
    "Zizaniopsis bonariensis (Balansa & Poitr.) Speg.": [
        {
            "family": "Poaceae",
            "phylum": "Tracheophyta",
            "order": "Poales",
            "genus": "Zizaniopsis",
            "species": "Zizaniopsis bonariensis",
            "class": "Liliopsida",
            "recordedBy": "",
            "decimalLatitude": -29.99,
            "decimalLongitude": -51.083333,
            "eventDate": "2006-02-14T00:00:00",
            "country": "Brazil",
            "stateProvince": "Rs",
            "locality": "."
        },
        {
            "family": "Poaceae",
            "phylum": "Tracheophyta",
            "order": "Poales",
            "genus": "Zizaniopsis",
            "species": "Zizaniopsis bonariensis",
            "class": "Liliopsida",
            "recordedBy": "Matzenbacher, NI",
            "decimalLatitude": 0.0,
            "decimalLongitude": 0.0,
            "eventDate": "1996-11-30T00:00:00",
            "country": "Brazil",
            "stateProvince": "Rs",
            "locality": "Fazenda S\u00e3o Maximiano"
        },
        {
            "family": "Poaceae",
            "phylum": "Tracheophyta",
            "order": "Poales",
            "genus": "Zizaniopsis",
            "species": "Zizaniopsis bonariensis",
            "class": "Liliopsida",
            "recordedBy": "Sara G. Tressens|M. Beccaceci|Ricardo O. Vanni",
            "decimalLatitude": "",
            "decimalLongitude": "",
            "eventDate": "1992-12-11T00:00:00",
            "country": "Argentina",
            "stateProvince": "Corrientes",
            "locality": "Reserva Nat. Prov. Ibera. Paso Picada. Costa W de la laguna Ibera"
        },
        {
            "family": "Poaceae",
            "phylum": "Tracheophyta",
            "order": "Poales",
            "genus": "Zizaniopsis",
            "species": "Zizaniopsis bonariensis",
            "class": "Liliopsida",
            "recordedBy": "Schwarzbold, A",
            "decimalLatitude": 0.0,
            "decimalLongitude": 0.0,
            "eventDate": "1981-02-02T00:00:00",
            "country": "Brazil",
            "stateProvince": "Rs",
            "locality": "Lagoa Figueira, sul de palmares"
        },
        {
            "family": "Poaceae",
            "phylum": "Tracheophyta",
            "order": "Poales",
            "genus": "Zizaniopsis",
            "species": "Zizaniopsis bonariensis",
            "class": "Liliopsida",
            "recordedBy": "Irgang, BE; et al.",
            "decimalLatitude": 0.0,
            "decimalLongitude": 0.0,
            "eventDate": "1981-03-01T00:00:00",
            "country": "Brazil",
            "stateProvince": "Rs",
            "locality": "Taim"
        },
        {
            "family": "Poaceae",
            "phylum": "Tracheophyta",
            "order": "Poales",
            "genus": "Zizaniopsis",
            "species": "Zizaniopsis bonariensis",
            "class": "Liliopsida",
            "recordedBy": "R\u00fagolo, Z",
            "decimalLatitude": 0.0,
            "decimalLongitude": 0.0,
            "eventDate": "1980-11-02T00:00:00",
            "country": "Argentina",
            "stateProvince": "",
            "locality": "[...] Las Violetas"
        },
        {
            "family": "Poaceae",
            "phylum": "Tracheophyta",
            "order": "Poales",
            "genus": "Zizaniopsis",
            "species": "Zizaniopsis bonariensis",
            "class": "Liliopsida",
            "recordedBy": "Zulma E. R\u00fagolo de Agrasar",
            "decimalLatitude": "",
            "decimalLongitude": "",
            "eventDate": "1980-11-02T00:00:00",
            "country": "Argentina",
            "stateProvince": "",
            "locality": "Pdo. Gral. Lavalle, Ecia. Las Violetas."
        },
        {
            "family": "Poaceae",
            "phylum": "Tracheophyta",
            "order": "Poales",
            "genus": "Zizaniopsis",
            "species": "Zizaniopsis bonariensis",
            "class": "Liliopsida",
            "recordedBy": "Fern\u00e1ndez",
            "decimalLatitude": "",
            "decimalLongitude": "",
            "eventDate": "1978-03-08T00:00:00",
            "country": "Argentina",
            "stateProvince": "Corrientes",
            "locality": "Estancia lavalle."
        },
        {
            "family": "Poaceae",
            "phylum": "Tracheophyta",
            "order": "Poales",
            "genus": "Zizaniopsis",
            "species": "Zizaniopsis bonariensis",
            "class": "Liliopsida",
            "recordedBy": "Waechter, JL",
            "decimalLatitude": 0.0,
            "decimalLongitude": 0.0,
            "eventDate": "1978-12-04T00:00:00",
            "country": "Brazil",
            "stateProvince": "Rs",
            "locality": "Esta\u00e7\u00e3o Ecol\u00f3gica do Taim"
        },
        {
            "family": "Poaceae",
            "phylum": "Tracheophyta",
            "order": "Poales",
            "genus": "Zizaniopsis",
            "species": "Zizaniopsis bonariensis",
            "class": "Liliopsida",
            "recordedBy": "Quar\u00edn, C; et al.",
            "decimalLatitude": 0.0,
            "decimalLongitude": 0.0,
            "eventDate": "1974-12-06T00:00:00",
            "country": "Argentina",
            "stateProvince": "Corrientes",
            "locality": "Santo Tom\u00e9 Galarza"
        },
        {
            "family": "Poaceae",
            "phylum": "Tracheophyta",
            "order": "Poales",
            "genus": "Zizaniopsis",
            "species": "Zizaniopsis bonariensis",
            "class": "Liliopsida",
            "recordedBy": "Valls, JFM; et al.",
            "decimalLatitude": 0.0,
            "decimalLongitude": 0.0,
            "eventDate": "1973-12-03T00:00:00",
            "country": "Brazil",
            "stateProvince": "Rs",
            "locality": "estrada S\u00e3o Pedro do Sul-Jaguari 38 Km ap\u00f3s S\u00e3o Pedro"
        },
        {
            "family": "Poaceae",
            "phylum": "Tracheophyta",
            "order": "Poales",
            "genus": "Zizaniopsis",
            "species": "Zizaniopsis bonariensis",
            "class": "Liliopsida",
            "recordedBy": "Howard S. Irwin|S.F. da Fons\u00eaca|R. Souza|R. Reis dos Santos|J. Ramos",
            "decimalLatitude": "",
            "decimalLongitude": "",
            "eventDate": "1970-03-23T00:00:00",
            "country": "Brazil",
            "stateProvince": "Minas Gerais",
            "locality": "River bank. Cut-over slope forest, ca. 15 km N. of S\u00e3o Jo\u00e3o da Chapada."
        },
        {
            "family": "Poaceae",
            "phylum": "Tracheophyta",
            "order": "Poales",
            "genus": "Zizaniopsis",
            "species": "Zizaniopsis bonariensis",
            "class": "Liliopsida",
            "recordedBy": "Burkart, A",
            "decimalLatitude": 0.0,
            "decimalLongitude": 0.0,
            "eventDate": "1962-12-09T00:00:00",
            "country": "Argentina",
            "stateProvince": "Buenos Aires",
            "locality": ""
        },
        {
            "family": "Poaceae",
            "phylum": "Tracheophyta",
            "order": "Poales",
            "genus": "Zizaniopsis",
            "species": "Zizaniopsis bonariensis",
            "class": "Liliopsida",
            "recordedBy": "Troels M. Pedersen",
            "decimalLatitude": "",
            "decimalLongitude": "",
            "eventDate": "1961-02-17T00:00:00",
            "country": "Argentina",
            "stateProvince": "Corrientes",
            "locality": "\"Estancia, Santa Teresa\"."
        },
        {
            "family": "Poaceae",
            "phylum": "Tracheophyta",
            "order": "Poales",
            "genus": "Zizaniopsis",
            "species": "Zizaniopsis bonariensis",
            "class": "Liliopsida",
            "recordedBy": "J. da Costa Sacco",
            "decimalLatitude": 0.0,
            "decimalLongitude": 0.0,
            "eventDate": "1957-12-02T00:00:00",
            "country": "Brazil",
            "stateProvince": "Rio Grande do Sul",
            "locality": "I.A.S. - Pelotas.  Canal I.A.S. - S. Gon\u00e7alo, bra\u00e7o de liga\u00e7ao com o arroio Pe. Doutor"
        },
        {
            "family": "Poaceae",
            "phylum": "Tracheophyta",
            "order": "Poales",
            "genus": "Zizaniopsis",
            "species": "Zizaniopsis bonariensis",
            "class": "Liliopsida",
            "recordedBy": "Pedersen TM",
            "decimalLatitude": "",
            "decimalLongitude": "",
            "eventDate": "1951-02-17T00:00:00",
            "country": "Argentina",
            "stateProvince": "",
            "locality": "Estancia Santa Teresa. Dep. Mburucuya. Prov. Corrientes."
        },
        {
            "family": "Poaceae",
            "phylum": "Tracheophyta",
            "order": "Poales",
            "genus": "Zizaniopsis",
            "species": "Zizaniopsis bonariensis",
            "class": "Liliopsida",
            "recordedBy": "Armando T. Hunziker",
            "decimalLatitude": "",
            "decimalLongitude": "",
            "eventDate": "1946-11-26T00:00:00",
            "country": "Argentina",
            "stateProvince": "Buenos Aires",
            "locality": "Las Palmas."
        },
        {
            "family": "Poaceae",
            "phylum": "Tracheophyta",
            "order": "Poales",
            "genus": "Zizaniopsis",
            "species": "Zizaniopsis bonariensis",
            "class": "Liliopsida",
            "recordedBy": "Antonio Krapovickas",
            "decimalLatitude": "",
            "decimalLongitude": "",
            "eventDate": "1946-11-26T00:00:00",
            "country": "Argentina",
            "stateProvince": "Buenos Aires",
            "locality": "Las Palmas Zral. Uribure."
        },
        {
            "family": "Poaceae",
            "phylum": "Tracheophyta",
            "order": "Poales",
            "genus": "Zizaniopsis",
            "species": "Zizaniopsis bonariensis",
            "class": "Liliopsida",
            "recordedBy": "Jason R. Swallen",
            "decimalLatitude": "",
            "decimalLongitude": "",
            "eventDate": "1945-10-31T00:00:00",
            "country": "Brazil",
            "stateProvince": "Rio Grande do Sul",
            "locality": "Sao Goncaies, instituto Agronomico do Sul, Pelotas. Wet ground along canal to arroyo."
        },
        {
            "family": "Poaceae",
            "phylum": "Tracheophyta",
            "order": "Poales",
            "genus": "Zizaniopsis",
            "species": "Zizaniopsis bonariensis",
            "class": "Liliopsida",
            "recordedBy": "Rodriguez",
            "decimalLatitude": 0.0,
            "decimalLongitude": 0.0,
            "eventDate": "1912-06-23T00:00:00",
            "country": "Argentina",
            "stateProvince": "Buenos Aires",
            "locality": "Quilmes"
        },
        {
            "family": "Poaceae",
            "phylum": "Tracheophyta",
            "order": "Poales",
            "genus": "Zizaniopsis",
            "species": "Zizaniopsis bonariensis",
            "class": "Liliopsida",
            "recordedBy": "Balansa B",
            "decimalLatitude": "",
            "decimalLongitude": "",
            "eventDate": "1875-11-14T00:00:00",
            "country": "Paraguay",
            "stateProvince": "",
            "locality": "PL. du Paraguay., Bu\u00e9nos - aires, dans les marais."
        },
        {
            "family": "Poaceae",
            "phylum": "Tracheophyta",
            "order": "Poales",
            "genus": "Zizaniopsis",
            "species": "Zizaniopsis bonariensis",
            "class": "Liliopsida",
            "recordedBy": "Balansa B",
            "decimalLatitude": "",
            "decimalLongitude": "",
            "eventDate": "1875-11-14T00:00:00",
            "country": "Paraguay",
            "stateProvince": "",
            "locality": "PL. du Paraguay., Bu\u00e9nos - aires, dans les marais."
        },
        {
            "family": "Poaceae",
            "phylum": "Tracheophyta",
            "order": "Poales",
            "genus": "Zizaniopsis",
            "species": "Zizaniopsis bonariensis",
            "class": "Liliopsida",
            "recordedBy": "Unknown",
            "decimalLatitude": "",
            "decimalLongitude": "",
            "eventDate": "1875-11-07T00:00:00",
            "country": "Paraguay",
            "stateProvince": "",
            "locality": "Paseo de Julio, \u00e0 Buenos - Aires. *."
        },
        {
            "family": "Poaceae",
            "phylum": "Tracheophyta",
            "order": "Poales",
            "genus": "Zizaniopsis",
            "species": "Zizaniopsis bonariensis",
            "class": "Liliopsida",
            "recordedBy": "",
            "decimalLatitude": -37.615321,
            "decimalLongitude": -57.423687,
            "eventDate": None,
            "country": "Argentina",
            "stateProvince": "Buenos Aires",
            "locality": "Estancia \"Nahuel Ruca\", m\u00e1rgen de Laguna Nahuel Ruca"
        },
        {
            "family": "Poaceae",
            "phylum": "Tracheophyta",
            "order": "Poales",
            "genus": "Zizaniopsis",
            "species": "Zizaniopsis bonariensis",
            "class": "Liliopsida",
            "recordedBy": "",
            "decimalLatitude": "",
            "decimalLongitude": "",
            "eventDate": None,
            "country": "Argentina",
            "stateProvince": "Buenos Aires",
            "locality": "Conchitas"
        },
        {
            "family": "Poaceae",
            "phylum": "Tracheophyta",
            "order": "Poales",
            "genus": "Zizaniopsis",
            "species": "Zizaniopsis bonariensis",
            "class": "Liliopsida",
            "recordedBy": "",
            "decimalLatitude": "",
            "decimalLongitude": "",
            "eventDate": None,
            "country": "Argentina",
            "stateProvince": "Buenos Aires",
            "locality": ""
        },
        {
            "family": "Poaceae",
            "phylum": "Tracheophyta",
            "order": "Poales",
            "genus": "Zizaniopsis",
            "species": "Zizaniopsis bonariensis",
            "class": "Liliopsida",
            "recordedBy": "",
            "decimalLatitude": "",
            "decimalLongitude": "",
            "eventDate": None,
            "country": "Argentina",
            "stateProvince": "Entre R\u00edos",
            "locality": "M\u00e9danos"
        },
        {
            "family": "Poaceae",
            "phylum": "Tracheophyta",
            "order": "Poales",
            "genus": "Zizaniopsis",
            "species": "Zizaniopsis bonariensis",
            "class": "Liliopsida",
            "recordedBy": "",
            "decimalLatitude": "",
            "decimalLongitude": "",
            "eventDate": None,
            "country": "Argentina",
            "stateProvince": "Buenos Aires",
            "locality": "Delta del Paran\u00e1, R\u00edo Capit\u00e1n y Paran\u00e1 de las Palmas"
        },
        {
            "family": "Poaceae",
            "phylum": "Tracheophyta",
            "order": "Poales",
            "genus": "Zizaniopsis",
            "species": "Zizaniopsis bonariensis",
            "class": "Liliopsida",
            "recordedBy": "W.G. Herter",
            "decimalLatitude": "",
            "decimalLongitude": "",
            "eventDate": None,
            "country": "Uruguay",
            "stateProvince": "",
            "locality": ""
        },
        {
            "family": "Poaceae",
            "phylum": "Tracheophyta",
            "order": "Poales",
            "genus": "Zizaniopsis",
            "species": "Zizaniopsis bonariensis",
            "class": "Liliopsida",
            "recordedBy": "Jos\u00e9 F.M. Valls|A. Pott|Hilda M. Longhi-Wagner",
            "decimalLatitude": "",
            "decimalLongitude": "",
            "eventDate": None,
            "country": "Brazil",
            "stateProvince": "",
            "locality": "General Vargas, Estr. S. Pedro do Sul-Jaguari, 38 km apos S. Pedro-Varzea do rio Toropi, jun to a ponte de concreto de + 80 de extens\u00e3o."
        },
        {
            "family": "Poaceae",
            "phylum": "Tracheophyta",
            "order": "Poales",
            "genus": "Zizaniopsis",
            "species": "Zizaniopsis bonariensis",
            "class": "Liliopsida",
            "recordedBy": "",
            "decimalLatitude": "",
            "decimalLongitude": "",
            "eventDate": None,
            "country": "Argentina",
            "stateProvince": "Buenos Aires",
            "locality": "Avellaneda ?"
        },
        {
            "family": "Poaceae",
            "phylum": "Tracheophyta",
            "order": "Poales",
            "genus": "Zizaniopsis",
            "species": "Zizaniopsis bonariensis",
            "class": "Liliopsida",
            "recordedBy": "",
            "decimalLatitude": "",
            "decimalLongitude": "",
            "eventDate": None,
            "country": "Argentina",
            "stateProvince": "Buenos Aires",
            "locality": "Quilmes"
        },
        {
            "family": "Poaceae",
            "phylum": "Tracheophyta",
            "order": "Poales",
            "genus": "Zizaniopsis",
            "species": "Zizaniopsis bonariensis",
            "class": "Liliopsida",
            "recordedBy": "",
            "decimalLatitude": "",
            "decimalLongitude": "",
            "eventDate": None,
            "country": "Argentina",
            "stateProvince": "Entre R\u00edos",
            "locality": "Pranacito"
        },
        {
            "family": "Poaceae",
            "phylum": "Tracheophyta",
            "order": "Poales",
            "genus": "Zizaniopsis",
            "species": "Zizaniopsis bonariensis",
            "class": "Liliopsida",
            "recordedBy": "",
            "decimalLatitude": "",
            "decimalLongitude": "",
            "eventDate": None,
            "country": "Argentina",
            "stateProvince": "Buenos Aires",
            "locality": "Laguna San Vicente"
        },
        {
            "family": "Poaceae",
            "phylum": "Tracheophyta",
            "order": "Poales",
            "genus": "Zizaniopsis",
            "species": "Zizaniopsis bonariensis",
            "class": "Liliopsida",
            "recordedBy": "",
            "decimalLatitude": "",
            "decimalLongitude": "",
            "eventDate": None,
            "country": "Argentina",
            "stateProvince": "Buenos Aires",
            "locality": "\"El Toro\", Rosas F.C.S."
        },
        {
            "family": "Poaceae",
            "phylum": "Tracheophyta",
            "order": "Poales",
            "genus": "Zizaniopsis",
            "species": "Zizaniopsis bonariensis",
            "class": "Liliopsida",
            "recordedBy": "Balansa B",
            "decimalLatitude": "",
            "decimalLongitude": "",
            "eventDate": None,
            "country": "Paraguay",
            "stateProvince": "",
            "locality": "Monoique., Buenos-ayres, dans les marais."
        },
        {
            "family": "Poaceae",
            "phylum": "Tracheophyta",
            "order": "Poales",
            "genus": "Zizaniopsis",
            "species": "Zizaniopsis bonariensis",
            "class": "Liliopsida",
            "recordedBy": "",
            "decimalLatitude": "",
            "decimalLongitude": "",
            "eventDate": None,
            "country": "Argentina",
            "stateProvince": "La Pampa",
            "locality": ""
        }
    ]
}

class test_getNames(unittest.TestCase):
    def test(self):
        self.assertEqual(gbif_api.getOccurrences(test_caseImput), test_caseOutput)

if __name__ == '__main__':
    unittest.main()